#pragma once
#ifndef SIREN_PhaseSpaceChannel_H
#define SIREN_PhaseSpaceChannel_H

#include <memory>
#include <string>
#include <vector>

#include "SIREN/dataclasses/PhaseSpaceConvention.h"

namespace siren { namespace dataclasses { class InteractionRecord; } }
namespace siren { namespace detector { class DetectorModel; } }
namespace siren { namespace utilities { class SIREN_random; } }

namespace siren {
namespace injection {

// Import new types
using PhaseSpaceTopology = siren::dataclasses::PhaseSpaceTopology;
using PhaseSpaceMeasure = siren::dataclasses::PhaseSpaceMeasure;
using siren::dataclasses::PhaseSpaceTopologyName;
using siren::dataclasses::PhaseSpaceMeasureName;
using siren::dataclasses::MeasureConvertibilityGroup;
using siren::dataclasses::PhaseSpaceCompatible;

// Legacy aliases
using PhaseSpaceConvention = siren::dataclasses::PhaseSpaceConvention;
using siren::dataclasses::PhaseSpaceConventionName;

// A single parameterization of a final-state phase space, used
// in multi-channel importance sampling of interaction/decay
// kinematics.
//
// Each channel knows how to:
//   1. Sample final-state kinematics (writing into an InteractionRecord)
//   2. Evaluate its sampling density at ANY valid phase-space point
//
// Property (2) is essential for multi-channel integration: when
// combining N channels with weights alpha_i, the combined density
// is g(x) = sum_i alpha_i * g_i(x), which requires evaluating
// every channel's density at every sampled point.
//
// Each channel reports a Topology (structural shape of the final
// state) and a Measure (what variables the density is differential
// in).  Channels in a MultiChannelPhaseSpace must share the same
// topology and have measures in the same convertibility group.
class PhaseSpaceChannel {
public:
    virtual ~PhaseSpaceChannel() = default;

    // Sample final-state kinematics.
    //
    // Reads the primary momentum, interaction vertex, and target
    // from the record.  Writes secondary momenta, masses, and types
    // into the record.
    //
    // The record's signature (secondary types) must already be set
    // to indicate which final state this channel should produce.
    virtual void Sample(
        std::shared_ptr<siren::utilities::SIREN_random> random,
        std::shared_ptr<siren::detector::DetectorModel const> detector_model,
        siren::dataclasses::InteractionRecord & record
    ) const = 0;

    // Evaluate this channel's sampling density at the phase-space
    // point described by the record.
    //
    // Must be evaluable for ANY valid phase-space point for this
    // final state, not just points generated by this channel.
    virtual double Density(
        std::shared_ptr<siren::detector::DetectorModel const> detector_model,
        siren::dataclasses::InteractionRecord const & record
    ) const = 0;

    virtual std::string Name() const = 0;

    // Structural shape of the final state.
    virtual PhaseSpaceTopology Topology() const = 0;

    // What variables the density is differential in.
    virtual PhaseSpaceMeasure Measure() const = 0;

    // Legacy interface. Default implementation derives from Topology+Measure.
    virtual PhaseSpaceConvention Convention() const;

    // True if this channel contributes a genuine (non-fallback) proposal at the
    // phase-space point in `record`.  A detector-directed channel overrides this
    // to return false when it falls back to its shared isotropic 1/4pi
    // distribution (directing impossible/unnecessary); channels with no fallback
    // notion (physical, isotropic) are always "active".  Lets the optimizer
    // discount a channel's variance on its fallback events and, via
    // NestedMixtureChannel, drive a whole group of fallback directors down with
    // a single outer weight.
    virtual bool DirectingActive(
        siren::dataclasses::InteractionRecord const &) const { return true; }
};

// A set of PhaseSpaceChannels combined with weights for
// multi-channel sampling.
//
// When sampling: pick channel i with probability alpha_i,
// then call channel_i.Sample().
//
// The combined generation density at any point is:
//   g(x) = sum_i alpha_i * g_i(x)
//
// All channels must share the same Topology.  If channels report
// different Measures within the same convertibility group, Density()
// auto-converts via analytic Jacobians.
struct MultiChannelPhaseSpace {
    std::vector<std::shared_ptr<PhaseSpaceChannel>> channels;
    std::vector<double> weights;  // alpha_i, must sum to 1
    mutable bool compatibility_warning_emitted = false;

    // Kleiss-Pittau weight-tuning accumulators.  These are transient runtime
    // state -- the mixture owns its own per-channel variance statistics, fed by
    // Accumulate() and consumed by UpdateWeights() -- and are intentionally NOT
    // serialized.  kp_accumulator_[i] is the running sum of the bare per-channel
    // contribution w^2 * g_i^conv / g; kp_count_ is the number of accumulated
    // points.
    std::vector<double> kp_accumulator_;
    long kp_count_ = 0;

    // Per-channel selection-probability sums (p_i = alpha_i*g_i/g) over
    // successful and failed trees, used by the chain optimizer's failure penalty
    // to inflate W_i for channels that disproportionately feed failed events.
    // Also transient runtime state, not serialized.
    std::vector<double> kp_succ_select_;
    std::vector<double> kp_fail_select_;

    // Sample from the multi-channel mixture.
    // Returns the index of the channel that was used.
    int Sample(
        std::shared_ptr<siren::utilities::SIREN_random> random,
        std::shared_ptr<siren::detector::DetectorModel const> detector_model,
        siren::dataclasses::InteractionRecord & record
    ) const;

    // Evaluate the combined density g(x) = sum_i alpha_i * g_i(x),
    // auto-converting measures where needed.
    double Density(
        std::shared_ptr<siren::detector::DetectorModel const> detector_model,
        siren::dataclasses::InteractionRecord const & record
    ) const;

    // Per-channel breakdown of Density(): element i is channel i's
    // alpha-weighted contribution in the common measure, i.e.
    //   weights[i] * ConvertDensity(channels[i]->Density(...), ...).
    // The elements sum to Density().  Surfacing them lets an optimizer form
    // the Kleiss-Pittau per-channel statistic without re-evaluating each
    // channel from Python, and without the measure mismatch that
    // re-evaluating the unconverted g_i against the common-measure g would
    // introduce.
    std::vector<double> DensityBreakdown(
        std::shared_ptr<siren::detector::DetectorModel const> detector_model,
        siren::dataclasses::InteractionRecord const & record
    ) const;

    // --- Kleiss-Pittau weight tuning (the mixture owns its statistics) ---

    // Fold one sampled point into the per-channel accumulators.  `weight` is the
    // importance weight w = f/g (single vertex) or the total event weight
    // (chain); channel i is credited w^2 * g_i^conv / g, where g is THIS
    // mixture's density, unless discount_fallback is set and channel i reports
    // DirectingActive(record) == false (its isotropic fallback), in which case it
    // is skipped so a pure-fallback director is driven down.  With `recurse`, a
    // NestedMixtureChannel's inner channels are credited too, against this same
    // outer g.  Points with g <= 0 or non-finite g are ignored (not counted).
    void Accumulate(
        std::shared_ptr<siren::detector::DetectorModel const> detector_model,
        siren::dataclasses::InteractionRecord const & record,
        double weight,
        bool discount_fallback = true,
        bool recurse = true);

    // Apply one Kleiss-Pittau update from the accumulated statistics, then reset
    // them.  W_i = kp_accumulator_[i] / kp_count_; the candidate is sqrt(W_i)
    // ("sqrt_W", memoryless) or weights[i]*sqrt(W_i) ("alpha_sqrt_W", canonical),
    // normalized, floored at min_weight and renormalized, then blended with the
    // current weights as damping*candidate + (1-damping)*old.  A degenerate batch
    // (no positive contributions, or no points) leaves the weights unchanged.
    // With `recurse`, nested mixtures are updated too.
    // failure_mode controls the chain failure handling (only active when
    // AccumulateSelection data is present): "throughput" (default) down-weights
    // lossy channels (W_i *= 1-f_i; tracks the successful contribution, converges
    // fastest, batch-insensitive), "ignore" leaves W untouched (same fixed point,
    // slower), "coverage" up-weights lossy channels (W_i /= 1-f_i, the original
    // behavior; tends to retain them).
    void UpdateWeights(
        std::string const & update_rule,
        double damping,
        double min_weight,
        bool recurse = true,
        std::string const & failure_mode = "throughput");

    // Zero the accumulators (optionally recursing into nested mixtures).
    void ResetAccumulators(bool recurse = true);

    // Fold one tree's per-channel selection probability p_i = alpha_i*g_i/g into
    // the success (failed == false) or failure (failed == true) accumulator.
    // The chain optimizer's UpdateWeights then inflates W_i by 1/(1 - f_i), with
    // f_i the channel's failed-selection fraction, so a channel that mostly feeds
    // failed events is penalized.  Outer-channel only (the penalty is not applied
    // to nested groups).
    void AccumulateSelection(
        std::shared_ptr<siren::detector::DetectorModel const> detector_model,
        siren::dataclasses::InteractionRecord const & record,
        bool failed);

    // Return the common topology. Throws if channels disagree.
    PhaseSpaceTopology CommonTopology() const;

    // Return the preferred common measure (majority vote, priority tie-break).
    PhaseSpaceMeasure CommonMeasure() const;

    // Legacy interface.
    PhaseSpaceConvention CommonConvention() const;

    // Validate topology and measure compatibility.
    // Returns diagnostics (empty if all checks pass).
    // Throws on topology mismatch or incompatible measure groups.
    std::vector<std::string> ValidateChannels() const;

    // Structural validation: sample from each channel and verify
    // that every OTHER channel returns a finite, non-negative
    // density at that point.
    //
    // Returns a list of diagnostic strings (empty if all checks pass).
    std::vector<std::string> ValidateChannelDensities(
        std::shared_ptr<siren::utilities::SIREN_random> random,
        std::shared_ptr<siren::detector::DetectorModel const> detector_model,
        siren::dataclasses::InteractionRecord template_record,
        int samples_per_channel = 100
    ) const;

    // Legacy aliases
    std::vector<std::string> ValidateConventions() const { return ValidateChannels(); }

private:
    void WarnOnIncompatibility() const;

    // Single code path behind Density() and DensityBreakdown(): loops the
    // channels once, converting each g_i to the common measure.  Returns the
    // summed density g.  When `weighted` is non-null it is filled with the
    // alpha-weighted contributions weights[i]*g_i^conv (which sum to g); when
    // `bare` is non-null it is filled with the un-weighted converted densities
    // g_i^conv (consumed directly by the KP accumulator, no divide-by-alpha).
    double ComputeContributions(
        std::shared_ptr<siren::detector::DetectorModel const> detector_model,
        siren::dataclasses::InteractionRecord const & record,
        std::vector<double> * weighted,
        std::vector<double> * bare
    ) const;

    // Recursive primitive behind Accumulate(): credit each channel's bare
    // converted density against the supplied outer denominator g_denom (so a
    // nested mixture's inner channels share the outer g), counting the point
    // once per mixture level.
    void CreditAgainst(
        std::shared_ptr<siren::detector::DetectorModel const> detector_model,
        siren::dataclasses::InteractionRecord const & record,
        double w2,
        double g_denom,
        bool discount_fallback,
        bool recurse);
};

// A PhaseSpaceChannel that wraps a MultiChannelPhaseSpace, so an entire
// sub-mixture can be used as ONE channel inside an outer mixture.  Sampling
// and density delegate to the inner mixture; its weights stay reachable (via
// `mixture`) so an optimizer can tune them as a nested level.  Topology and
// Measure are the inner mixture's common values, so an outer mixture treats
// the nested channel exactly like any other channel of that topology/measure.
//
// This lets the geometric sub-structure (which target volumes, with what
// coefficients) be encapsulated and optimized separately from the outer,
// physics-level blend (physical / isotropic / detector-directed).
class NestedMixtureChannel : public PhaseSpaceChannel {
public:
    std::shared_ptr<MultiChannelPhaseSpace> mixture;
    std::string label = "NestedMixture";

    NestedMixtureChannel() = default;
    explicit NestedMixtureChannel(
        std::shared_ptr<MultiChannelPhaseSpace> mixture_)
        : mixture(mixture_) {}

    void Sample(
        std::shared_ptr<siren::utilities::SIREN_random> random,
        std::shared_ptr<siren::detector::DetectorModel const> detector_model,
        siren::dataclasses::InteractionRecord & record
    ) const override;

    double Density(
        std::shared_ptr<siren::detector::DetectorModel const> detector_model,
        siren::dataclasses::InteractionRecord const & record
    ) const override;

    std::string Name() const override;
    PhaseSpaceTopology Topology() const override;
    PhaseSpaceMeasure Measure() const override;

    // The group genuinely directs if ANY member does, so a group of directed
    // channels that are all in their isotropic fallback reports inactive and the
    // optimizer can drive the whole group down with one weight.
    bool DirectingActive(
        siren::dataclasses::InteractionRecord const & record) const override;
};

} // namespace injection
} // namespace siren

#endif // SIREN_PhaseSpaceChannel_H
