#pragma once
#ifndef SIREN_PhaseSpaceChannel_H
#define SIREN_PhaseSpaceChannel_H

#include <memory>
#include <string>
#include <vector>

namespace siren { namespace dataclasses { class InteractionRecord; } }
namespace siren { namespace detector { class DetectorModel; } }
namespace siren { namespace utilities { class SIREN_random; } }

namespace siren {
namespace injection {

enum class PhaseSpaceConvention {
    RestFrameSolidAngle,
    LabFrameSolidAngle,
    Recursive2Body,
    Dalitz,
    HelicityAngles,
    BjorkenXY,
    MandelstamST,
    Custom
};

std::string PhaseSpaceConventionName(PhaseSpaceConvention convention);

// A single parameterization of a final-state phase space, used
// in multi-channel importance sampling of interaction/decay
// kinematics.
//
// Each channel knows how to:
//   1. Sample final-state kinematics (writing into an InteractionRecord)
//   2. Evaluate its sampling density at ANY valid phase-space point
//
// Property (2) is essential for multi-channel integration: when
// combining N channels with weights alpha_i, the combined density
// is g(x) = sum_i alpha_i * g_i(x), which requires evaluating
// every channel's density at every sampled point.
//
// The density is reported with respect to Convention().  All channels
// in a MultiChannelPhaseSpace must use the same convention unless all
// channels are explicitly tagged Custom.
class PhaseSpaceChannel {
public:
    virtual ~PhaseSpaceChannel() = default;

    // Sample final-state kinematics.
    //
    // Reads the primary momentum, interaction vertex, and target
    // from the record.  Writes secondary momenta, masses, and types
    // into the record.
    //
    // The record's signature (secondary types) must already be set
    // to indicate which final state this channel should produce.
    virtual void Sample(
        std::shared_ptr<siren::utilities::SIREN_random> random,
        std::shared_ptr<siren::detector::DetectorModel const> detector_model,
        siren::dataclasses::InteractionRecord & record
    ) const = 0;

    // Evaluate this channel's sampling density at the phase-space
    // point described by the record.
    //
    // Must be evaluable for ANY valid phase-space point for this
    // final state, not just points generated by this channel.
    // Returns the density with respect to LIPS measure.
    virtual double Density(
        std::shared_ptr<siren::detector::DetectorModel const> detector_model,
        siren::dataclasses::InteractionRecord const & record
    ) const = 0;

    virtual std::string Name() const = 0;

    virtual PhaseSpaceConvention Convention() const = 0;
};

// A set of PhaseSpaceChannels combined with weights for
// multi-channel sampling.
//
// When sampling: pick channel i with probability alpha_i,
// then call channel_i.Sample().
//
// The combined generation density at any point is:
//   g(x) = sum_i alpha_i * channel_i.Density(x)
struct MultiChannelPhaseSpace {
    std::vector<std::shared_ptr<PhaseSpaceChannel>> channels;
    std::vector<double> weights;  // alpha_i, must sum to 1
    mutable bool convention_warning_emitted = false;

    // Sample from the multi-channel mixture.
    // Returns the index of the channel that was used.
    int Sample(
        std::shared_ptr<siren::utilities::SIREN_random> random,
        std::shared_ptr<siren::detector::DetectorModel const> detector_model,
        siren::dataclasses::InteractionRecord & record
    ) const;

    // Evaluate the combined density g(x) = sum_i alpha_i * g_i(x)
    double Density(
        std::shared_ptr<siren::detector::DetectorModel const> detector_model,
        siren::dataclasses::InteractionRecord const & record
    ) const;

    // Return the preferred common convention for this channel set.
    // If the set mixes Custom with non-Custom channels, throws.
    // If the set mixes multiple non-Custom conventions, this picks a
    // stable convention for diagnostics using majority vote and a
    // numerical-stability tie break.
    PhaseSpaceConvention CommonConvention() const;

    // Validate channel conventions. Returns warning diagnostics for
    // non-Custom convention mismatches and throws if Custom is mixed
    // with any non-Custom convention.
    std::vector<std::string> ValidateConventions() const;

    // Structural validation: sample from each channel and verify
    // that every OTHER channel returns a finite, non-negative
    // density at that point.
    //
    // Returns a list of diagnostic strings (empty if all checks pass).
    // Each diagnostic describes which channel pair failed and why.
    //
    // This catches common bugs:
    //   - A channel returning 0 for events from another channel
    //     (incompatible measure or missing coverage)
    //   - A channel returning NaN or negative density
    //   - Extreme density ratios that indicate measure mismatch
    //
    // The template_record must have the correct primary momentum,
    // mass, interaction vertex, and signature already set.
    std::vector<std::string> ValidateChannels(
        std::shared_ptr<siren::utilities::SIREN_random> random,
        std::shared_ptr<siren::detector::DetectorModel const> detector_model,
        siren::dataclasses::InteractionRecord template_record,
        int samples_per_channel = 100
    ) const;

private:
    void WarnOnConventionMismatch() const;
};

} // namespace injection
} // namespace siren

#endif // SIREN_PhaseSpaceChannel_H
