# Override CMAKE_POLICY_VERSION_MINIMUM before adding subdirectory
set(TEMP_CMAKE_POLICY_VERSION_MINIMUM ${CMAKE_POLICY_VERSION_MINIMUM})
set(CMAKE_POLICY_VERSION_MINIMUM 3.5)
add_subdirectory(${PROJECT_SOURCE_DIR}/vendor/rk EXCLUDE_FROM_ALL)
set(CMAKE_POLICY_VERSION_MINIMUM ${TEMP_CMAKE_POLICY_VERSION_MINIMUM})
